### ISSUE TITLE
نسخه 5.5

### ISSUE THREAD

**Issue by webineh** [KaveNegar/kavenegar-laravel-notification#3]
سلام خیلی عالی فکر نمیکردم درستش کرده باشید

فقط روی نسخه 5.5  هماهنگش کنید

**Comment by bgsrb** [comment]
سلام

تست شد و مشکلی با این نسخه ندارد

راهنما نیز ویرایش شد
لطفا به لینک زیر مراجعه کنید
https://github.com/KaveNegar/kavenegar-laravel-notification#usage
