### ISSUE TITLE
"Unresolvable dependency resolving [Parameter #0 [ <required> $apiKey ]] in class Kavenegar\KavenegarApi"

### ISSUE THREAD

**Issue by erfanghoreishi** [KaveNegar/kavenegar-laravel-notification#4]
در لاراول ۵.۷ با پیغام خطای
 "Unresolvable dependency resolving [Parameter #0 [ <required> $apiKey ]] in class Kavenegar\KavenegarApi"
 مواجه می شوم درصورتی که کد ای پی آی مطابق دستور گفته شده در فایل سرویس و انو قرار دارد 
  'kavenegar' => [
        'key' => env('KAVENEGAR_API_KEY'),
        'sender' => env('KAVENEGAR_SENDER')
    ],

**Comment by palvaneh** [comment]
Please make sure that the service provider class exists in the vendor directory and it is registered properly and then check your configuration by running`config('services.kavenegar.key')` in the tinker
